export const jsonCards = [
  {
    bg: "bg-white",
    bgTitle: "bg-lemon",
    imgUrl: "./assets/img/cards/img-3.svg",
    toGoUrl: "#",
    firstTitle: "Search engine",
    secondTitle: "optimization",
    isLight: !1,
  },
  {
    bg: "bg-lemon",
    bgTitle: "bg-white",
    imgUrl: "./assets/img/cards/img-5.svg",
    toGoUrl: "#",
    firstTitle: "Pay-per-click",
    secondTitle: "optimization",
    isLight: !1,
  },
  {
    bg: "bg-dark",
    bgTitle: "bg-white",
    imgUrl: "./assets/img/cards/img.svg",
    toGoUrl: "#",
    firstTitle: "Social Media",
    secondTitle: "Marketing",
    isLight: !0,
  },
  {
    bg: null,
    bgTitle: "bg-lemon",
    imgUrl: "./assets/img/cards/img-6.svg",
    toGoUrl: "#",
    firstTitle: "Email",
    secondTitle: "Marketing",
    isLight: !1,
  },
  {
    bg: "bg-lemon",
    bgTitle: "bg-lemon",
    imgUrl: "./assets/img/cards/img-4.svg",
    toGoUrl: "#",
    firstTitle: "Content",
    secondTitle: "Creation",
    isLight: !1,
  },
  {
    bg: "bg-dark",
    bgTitle: "bg-white",
    imgUrl: "./assets/img/cards/img-2.svg",
    toGoUrl: "#",
    firstTitle: "Analytics and",
    secondTitle: "Tracking",
    isLight: !0,
  },
];